deployment:
  tasks:
    - export REPOPATH=/home/korobkabel/repositories/Korobka/*
    - export SITEPATH=/home/korobkabel/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH 